
{% set data = load_setup_py_data(setup_file='../../../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version')  %}

package:
  name: jetset
  version:  {{ version }}

source:
  path: ../../../

build:
  preserve_egg_dir: True
  script_env:
    - JETSETBESSELBUILD

requirements:

  build:
    - swig>3.0.0
    - python {{ python }}
    - setuptools
    - numpy>=1.22,<1.25

  run:
    - python>=3.8
    - setuptools
    - scipy>=1.5.0
    - numpy>=1.22,<1.25
    - astropy>=5.0.1,<=6
    - matplotlib>=3.1.0
    - future
    - iminuit>=2.0.0
    - corner
    - six
    - emcee>=3.0.0
    - pyyaml
    - pytest
    - numba>0.55
    - tqdm
    - jupyter
    - ipython
    - dill

about:
  home: https://github.com/andreatramacere/jetset
  license: BSD-3
  summary: ''
  license_family: BSD

extra:
  recipe-maintainers:
    - andreatramacere

