package:
  name: jetset
  version:  {{ os.environ.get('PKG_VERSION') }}

source:
  #git_url: https://github.com/andreatramacere/jetset.git
  #git_rev: develop
  path: /workdir/integration/jetset

build:
  # noarch_python: True
  preserve_egg_dir: True
  script_env:
    - name: JETSETSKIPBESSELBUILD
       value: TRUE

requirements:

  build:
    - swig
    - python

  run:
  - scipy
  - numpy
  - astropy>=4.0
  - matplotlib
  - future
  - iminuit
  - corner
  - six
  - emcee
  - pyyaml
  - pyqt



#tests:
#    imports:
#        - jetset
#        - jetset.jetmodel
#

#    commands:
#      - python -c 'import os;os.environ["MPLBACKEND"]="Agg"; from jetset.tests import test_functions; test_functions.test_short()'
#      test_functions.test_short()
#    # You can put tests commands to be run here.  Use this to tests that the
#    # entry points work.
#
#
#  # You can also put a file called run_test.py in the recipe that will be run
#  # at tests time.
#
#  requires:
#    - nose >=1.3.7
#    # Put any additional tests requirements here.  For example
#    # - nose



about:
  home: https://github.com/andreatramacere/jetset
  license: BSD-3
  summary: ''
  license_family: BSD

extra:
  recipe-maintainers:
    - andreatramacere